### ISSUE TITLE
Incompatibility with SodiumDynamicLights Fabric V1.0.2 on Minecraft version 1.21.1

### ISSUE THREAD

**Issue by Dibs218** [ZsoltMolnarrr/CombatSpells#75]
Game will fail to start when Spell Engine V1.0.5 and V1.0.4 is started with SodiumDynamicLights. The crash will blame SodiumDynamicLights however have not had the issue with other mods.

**Comment by ZsoltMolnarrr** [comment]
The issue is caused by SodiumDynamicLights.

https://github.com/txnimc/SodiumDynamicLights/issues/9

**Comment by ZsoltMolnarrr** [comment]
Even tho this is not a fault of Spell Engine, this Dynamic Lights integration will be removed from Spell Engine 1.0+, to avoid crashing, as neither replacement qualify reliable, due to missing unique entry point.

**Comment by ZsoltMolnarrr** [comment]
On 1.20.1, use LambDynamicLights, as it is specifcally supported by Spell Engine.
Other implementations are not, and they are not possible to be supported in parallel.

**Comment by LambdAurora** [comment]
I think this might be relevant since you seem to have been willing to support the original mod: LambDynamicLights has been updated to 1.21.1, tho it has a little change in the API for the entrypoint to work.
And for the foreseeable future I plan to maintain it more regularly than the last few months.
